### ISSUE TITLE
Sketch is cut off on different screen sizes

### ISSUE THREAD

**Issue by alexrabin** [fyzio/scribble#11]
I realized after I took the screenshots that I forgot a word so ignore that please lol.

When a sketch is drawn on a full screen iPad and then the view is in split screen the sketch is cut off.

![IMG_0288](https://user-images.githubusercontent.com/15949910/149642777-8a7987e1-fd8f-4b8d-9504-02011e7796f5.PNG)
![IMG_0290](https://user-images.githubusercontent.com/15949910/149642772-0f24ef65-891b-4437-a874-49b6df8297e2.PNG)
![IMG_0289](https://user-images.githubusercontent.com/15949910/149642776-29bedd77-6308-415e-b5cd-33913aa3d7cb.PNG)

I am using just the basic scribble widget

```
 Scribble(
  notifier: _notifier,
  drawPen: true,
),
```

**Comment by timcreatedit** [comment]
Hi, thanks for the issue and the screenshots!
Scribble by design doesn't have an opinion on how it is sized. Depending on what you want to happen, you could solve your problem by wrapping Scribble in a SizedBox with a fixed size which is then wrapped in a FittedBox, or SingleChildScrollView  for example.
Let me know if that fixes your issue or if I didn't consider something that needs addressing and I'll reopen the issue :)

**Comment by alexrabin** [comment]
@timcreatedit I've tried wrapping in a SizedBox and FittedBox but then there is an issue with the minWidthFactor of the pen. It changes from big to small depending on screen size

**Comment by timcreatedit** [comment]
That doesn't sound like the desired behavior, I'll take a look at it tomorrow!

**Comment by timcreatedit** [comment]
Ok "tomorrow" might have been a lie 😬 sorry I completely forgot about it
but the FittedBox > SizedBox approach works, and we are using it in our app.
It's important that the SizedBox is wrapping the Scribble Widget and both are wrapped in a FittedBox. Any problems that arise should have to do with the rest of your layout then.

What doesn't work is dynamically sizing the scribble widget depending on it's content, we might wanna look at that in the future but for now, a fixed size will need to do
